name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Instalar las dependencias de Node.js (npm install)
      - name: Install dependencies
        run: |
          npm install

  docker:
    needs: build  # Asegura que este paso se ejecute después de que la tarea "build" termine
    runs-on: ubuntu-latest

    steps:
      # Paso 3: Hacer checkout del código nuevamente (necesario por si hay cambios en el build)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 4: Loguearse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 5: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t kittyxcode/tu_imagen:${{ github.sha }} -t kittyxcode/tu_imagen:latest .

      # Paso 6: Subir la imagen Docker a Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push kittyxcode/tu_imagen:${{ github.sha }}
          docker push kittyxcode/tu_imagen:latest
